### ISSUE TITLE
DAO generates empty classes

### ISSUE THREAD

**Issue by carvaofficial** [AlwynW/PHPDAOGenerator#8]
I am trying to generate DAO from my MySQL database using Vanilla PHP or Codeigniter, and when it generates the classes they are empty, there is no code ... I would like you to help me solve it, thanks

**Comment by carvaofficial** [comment]
Fixed: When the Template class is called, an instantiation is made to call the constructor, but in Template.php there is no __construct (), therefore the .tpl files are never read
I will fork this repository with the update applied and a little documentation

**Comment by AlwynW** [comment]
Thanks @carvaofficial, it was on the timeline to fix for newer php versions but this repositiory it's no longer in active development. Glad you figured it out on your own.
